version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80
    depends_on:
      - python
    networks:
      - web
      - project
    environment:
      VIRTUAL_HOST: api.morehack.stride.one
      LETSENCRYPT_HOST: api.morehack.stride.one
      LETSENCRYPT_EMAIL: mark@siton.dev

  python:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-MoreTech}
      POSTGRES_USER: ${POSTGRES_USER:-MoreTech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-MoreTech}
    volumes:
      - "MoreTech:/var/lib/postgresql/data/"

volumes:
  MoreTech:

networks:
    web: # external network for hostname access
        external:
            name: web
    project: # internal network for project
